classDiagram
  direction LR

  class AcquisitionPivot {
    - instance$ AcquisitionPivot
    - motor SparkMax
    - pivotEncoder AbsoluteEncoder
    - pidController PIDController
    - enabled boolean
    - AcquisitionPivot()
    + getInstance()$ AcquisitionPivot
    + setAngleSetpoint(PivotSetpoint) void
    + setAngle(double) void
    + periodic() void
    + stopPivot() void
    + isAtSetpoint() boolean
    + getPosition() double
    + setEnabled(boolean) void
  }
