classDiagram
  direction LR

  class Dashboard {
    - autoChooser SendableChooser~AutonChoices~
    - delayChooser SendableChooser~Double~
    - instance$ Dashboard
    - Dashboard()
    + getInstance()$ Dashboard
    + periodic() void
    + clearTrajectory() void
    + getAutoChooser() SendableChooser~AutonChoices~
    + getDelayChooser() SendableChooser~Double~
    + setHubAligned(boolean) void
    + isManualModeEnabled() boolean
    + getManualShooterRPM() double
    + getManualShooterHoodAngle() double
    + nudgeManualShooterRPMBackward() void
    + nudgeManualShooterRPMForward() void
    + resetManualShooterRPM() void
    + nudgeManualShooterHoodAngleBackward() void
    + nudgeManualShooterHoodAngleForward() void
    + resetManualShooterHoodAngle() void
    + getAcquisitionTilt() double
  }
