classDiagram
  direction LR

  class Dashboard {
    - instance$ Dashboard
    + ROBOT_X$ SuppliedDashboardValue~Double~
    + ROBOT_Y$ SuppliedDashboardValue~Double~
    + ROBOT_ROT$ SuppliedDashboardValue~Double~
    + HUB_ALIGNED$ DashboardValue~Boolean~
    + MANUAL_MODE_ENABLED$ DashboardValue~Boolean~
    + MANUAL_SHOOTER_RPM$ EntryDashboardValue~Double~
    + MANUAL_SHOOTER_HOOD_ANGLE$ EntryDashboardValue~Double~
    + ACQUISITION_TILT$ DashboardValue~Double~
    + FIELD$ SendableDashboardValue~Field2d~
    + AUTO_CHOOSER$ DashboardValue~SendableChooser~AutonChoice~~
    + DELAY_CHOOSER$ DashboardValue~SendableChooser~Double~~
    - Dashboard()
    + getInstance()$ Dashboard
    + periodic() void
    + clearFieldTrajectory() void
  }
