classDiagram
  direction LR

  class Hood {
    <<inner>>
    - servoChannel ServoChannel
    - pulseRange ServoChannelConfig.PulseRange
    - Hood(ChannelId,PulseRange,ServoHubConfig)
    + enable() void
    + setAngle(double) void
  }
