classDiagram
  direction LR

  class Indexer {
    - instance$ Indexer
    - motor SparkFlex
    - controller SparkClosedLoopController
    - Indexer()
    + getInstance()$ Indexer
    + intake() void
    + dispose() void
    + stop() void
    + getRPM() double
  }
