classDiagram
  direction LR

  class Kicker {
    - kickerMotor SparkFlex
    - feederMotor SparkFlex
    - kickerController SparkClosedLoopController
    - feederController SparkClosedLoopController
    - instance$ Kicker
    - Kicker()
    + getInstance()$ Kicker
    + start() void
    + reverse() void
    + stop() void
  }
