classDiagram
  direction LR

  class Shooter {
    - instance$ Shooter
    - leftTop SparkMax
    - leftBottom SparkMax
    - rightTop SparkMax
    - rightBottom SparkMax
    - controller SparkClosedLoopController
    - encoder RelativeEncoder
    - sysIdRoutine SysIdRoutine
    - Shooter()
    + getInstance()$ Shooter
    + start(double) void
    + stop() void
    + getRPM() double
    + getTargetRPM() double
    + isAtTargetRPM() boolean
    + getTargetDistance(Pose2d) double
    + getTargetAngle(Pose2d) double
    + quasistaticSysId(Direction) Command
    + dynamicSysId(Direction) Command
  }
