classDiagram
  direction LR

  class ShooterHoods {
    - servoHub ServoHub
    - instance$ ShooterHoods
    - nearHood Hood
    - farHood Hood
    - ShooterHoods()
    + getInstance()$ ShooterHoods
    + getNearHood() Hood
    + getFarHood() Hood
  }
