classDiagram
  direction LR

  class Vision {
    - leftCamera PhotonCamera
    - rightCam PhotonCamera
    - leftCamPhotonEstimator PhotonPoseEstimator
    - rightCamPhotonEstimator PhotonPoseEstimator
    - leftCurStdDevs Matrix~N3,N1~
    - rightCurStdDevs Matrix~N3,N1~
    - leftStdDevSetter Consumer~Matrix~N3,N1~~
    - rightStdDevSetter Consumer~Matrix~N3,N1~~
    - instance$ Vision
    - Vision()
    + getInstance()$ Vision
    - estimateCameraPose(PhotonCamera,PhotonPoseEstimator,Matrix~N3,N1~,Consumer~Matrix~N3,N1~~) Optional~EstimatedRobotPose~
    + leftCamGetEstimatedGlobalPose() Optional~EstimatedRobotPose~
    + rightCamGetEstimatedGlobalPose() Optional~EstimatedRobotPose~
    - updateEstimationStdDevs(PhotonPoseEstimator,Optional~EstimatedRobotPose~,List~PhotonTrackedTarget~) Matrix~N3,N1~
    + getLeftEstimationStdDevs() Matrix~N3,N1~
    + getRightEstimationStdDevs() Matrix~N3,N1~
  }
