classDiagram
  direction BT
  class AlignToPoint {
    + AlignToPoint(Supplier~Translation2d~)
    + AlignToPoint(Supplier~Translation2d~, DoubleSupplier, DoubleSupplier)
    + end(boolean) void
    + execute() void
  }
  class AutoConstants {
    + AutoConstants()
  }
  class Auton {
    + Auton(Optional~Alliance~)
    - Pose2d initialPose
    # setInitialPose(PathPlannerTrajectory, Rotation2d) void
    + followPathCommand(PathPlannerPath) Command
    - setInitialPose(Pose2d) void
    Pose2d initialPose
  }
  class AutonChoices {
    <<enumeration>>
    - AutonChoices()
    + values() AutonChoices[]
    + valueOf(String) AutonChoices
  }
  class AutonSelector {
    - AutonSelector()
    - AutonSelector instance
    + chooseAuton() Auton
    + chooseDelay() double
    AutonSelector instance
  }
  class Dashboard {
    - Dashboard()
    - SendableChooser~AutonChoices~ autoChooser
    - SendableChooser~Double~ delayChooser
    - Dashboard instance
    + clearTrajectory() void
    + periodic() void
    SendableChooser~Double~ delayChooser
    SendableChooser~AutonChoices~ autoChooser
    Dashboard instance
  }
  class DashboardConstants {
    + DashboardConstants()
  }
  class DriveConstants {
    + DriveConstants()
  }
  class DriveTrain {
    - DriveTrain()
    - DriveTrain instance
    + drive(double, double, double, boolean) SwerveRequest
    + applyRequest(Supplier~SwerveRequest~) Command
    + addVisionMeasurement(Pose2d, double, Matrix~N3, N1~) void
    + periodic() void
    + addVisionMeasurement(Pose2d, double) void
    + setX() Command
    + sysIdDynamic(Direction) Command
    + sysIdQuasistatic(Direction) Command
    - startSimThread() void
    DriveTrain instance
    double y
    double x
    double rotation
  }
  class DriverJoystick {
    - DriverJoystick()
    - DriverJoystick instance
    - signChange(double, double) boolean
    - limitRate(double, double, SlewRateLimiter) double
    double forwardValue
    double sidewaysValue
    DriverJoystick instance
    double rotateValue
  }
  class IOConstants {
    + IOConstants()
  }
  class LeftShooter {
    - LeftShooter()
    - LeftShooter instance
    LeftShooter instance
  }
  class LeftShooter {
    + LeftShooter()
  }
  class LeftTaxi {
    ~ LeftTaxi(Optional~Alliance~)
  }
  class Main {
    - Main()
    + main(String[]) void
  }
  class NeoMotorConstants {
    + NeoMotorConstants()
  }
  class OperatorStates {
    <<enumeration>>
    - OperatorStates(String)
    + values() OperatorStates[]
    + valueOf(String) OperatorStates
  }
  class Paths {
    + Paths()
    PathPlannerPath rightPosTaxiPath
    PathPlannerPath leftPosTaxiPath
  }
  class PovPositions {
    <<enumeration>>
    - PovPositions()
    + values() PovPositions[]
    + valueOf(String) PovPositions
  }
  class RightShooter {
    - RightShooter()
    - RightShooter instance
    RightShooter instance
  }
  class RightShooter {
    + RightShooter()
  }
  class RightTaxi {
    ~ RightTaxi(Optional~Alliance~)
  }
  class Robot {
    + Robot()
    + testExit() void
    + testPeriodic() void
    + testInit() void
    + teleopPeriodic() void
    + teleopExit() void
    + disabledInit() void
    + disabledPeriodic() void
    + teleopInit() void
    + robotPeriodic() void
    + autonomousPeriodic() void
    + robotInit() void
    + autonomousInit() void
    + autonomousExit() void
    + disabledExit() void
  }
  class RobotStates {
    <<enumeration>>
    - RobotStates(String)
    + values() RobotStates[]
    + valueOf(String) RobotStates
  }
  class Shooter {
    # Shooter(int, int)
    + start(double) void
    + stop() void
    double RPM
    boolean atTargetRPM
  }
  class ShooterConstants {
    - ShooterConstants()
  }
  class SwagLights {
    - SwagLights()
    - SwagLights instance
    + setDefaultState() void
    + setEStop() void
    + periodic() void
    + stopSerialPort() void
    + setReadyState() void
    SwagLights instance
    String[] ledStates
    boolean disabled
  }
  class SwerveConstants {
    + SwerveConstants()
  }
  class Telemetry {
    + Telemetry(double)
    + telemeterize(SwerveDriveState) void
  }
  class Vision {
    - Vision()
    - Vision instance
    + setAlgaeMode() void
    + setAprilTagMode() void
    - updateEstimationStdDevs(PhotonPoseEstimator, Optional~EstimatedRobotPose~, List~PhotonTrackedTarget~, Matrix~N3, N1~) void
    + frontCamGetEstimatedGlobalPose() Optional~EstimatedRobotPose~
    + backCamGetEstimatedGlobalPose() Optional~EstimatedRobotPose~
    - estimateCameraPose(PhotonCamera, PhotonPoseEstimator, Matrix~N3, N1~) Optional~EstimatedRobotPose~
    Vision instance
    Matrix~N3, N1~ frontEstimationStdDevs
    Matrix~N3, N1~ backEstimationStdDevs
  }
  class VisionConstants {
    + VisionConstants()
  }
  class XboxController1038 {
    + XboxController1038(int)
    + deadband(double) double
    PovPositions POV
    double leftRumble
    double leftX
    double rightRumble
    double leftY
    double rightY
    double rightX
  }
  class build {
    + build()
    + getProperty(String) Object
    + run() Object
    + main(String[]) void
    + invokeMethod(String, Object) Object
    + setProperty(String, Object) void
    MetaClass metaClass
  }
  class settings {
    + settings()
    + getProperty(String) Object
    + run() Object
    + main(String[]) void
    + invokeMethod(String, Object) Object
    + setProperty(String, Object) void
    MetaClass metaClass
  }

  AlignToPoint "1" *--> "driveTrain 1" DriveTrain
  Auton "1" *--> "driveTrain 1" DriveTrain
  AutonSelector  -->  AutonChoices
  Dashboard "1" *--> "driveTrain 1" DriveTrain
  DriverJoystick "1" *--> "driveTrain 1" DriveTrain
  DriverJoystick "1" *--> "logger 1" Telemetry
  DriverJoystick  -->  XboxController1038
  LeftShooter  -->  Shooter
  ShooterConstants  -->  LeftShooter
  LeftTaxi  -->  Auton
  SwagLights  -->  OperatorStates
  XboxController1038  -->  PovPositions
  RightShooter  -->  Shooter
  ShooterConstants  -->  RightShooter
  RightTaxi  -->  Auton
  Robot "1" *--> "autonomousCommand 1" Auton
  Robot "1" *--> "autonSelector 1" AutonSelector
  Robot "1" *--> "driveTrain 1" DriveTrain
  Robot "1" *--> "swagLights 1" SwagLights
  Robot "1" *--> "vision 1" Vision
  SwagLights  -->  RobotStates
  SwagLights "1" *--> "operatorState 1" OperatorStates
  SwagLights "1" *--> "robotState 1" RobotStates
