classDiagram
  direction LR

  class XboxController1038 {
    - controller XboxController
    + XboxController1038(int port)
    + getPOV() PovPositions
    + deadband(double) double
    + getLeftY() double
    + getLeftX() double
    + getRightY() double
    + getRightX() double
    + setLeftRumble(double) void
    + setRightRumble(double) void
    + setRumble(double) void
  }
