classDiagram
  direction LR

  class DriverJoystick {
    - driveTrain DriveTrain
    - shooterHood ShooterHood
    - maxPower double
    - prevSideways double
    - prevForward double
    - prevRotate double
    ~ forwardLimiter SlewRateLimiter
    ~ sidewaysLimiter SlewRateLimiter
    ~ rotateLimiter SlewRateLimiter
    ~ forwardFilter LinearFilter
    ~ sidewaysFilter LinearFilter
    - logger Telemetry
    - instance$ DriverJoystick
    - DriverJoystick()
    + getInstance()$ DriverJoystick
    - getSidewaysValue() double
    - getForwardValue() double
    - getRotateValue() double
    - limitRate(double,double,SlewRateLimiter) double
    - signChange(double,double) boolean
  }
