classDiagram
  direction LR

  class AutonChoices {
    <<enumeration>>
    NoAuto
    LeftTrenchAuto
    RightTrenchAuto
    LeftPreloadAuto
    MiddlePreloadAuto
    RightPreloadAuto
    DepotAuto
    ShooterSysID
  }
