classDiagram
  direction LR

  class AutonSelector {
    ~ autoChooser SendableChooser~AutonChoices~
    ~ delayChooser SendableChooser~Double~
    - instance$ AutonSelector
    - AutonSelector()
    + getInstance()$ AutonSelector
    + chooseAuton() Auton
    + chooseDelay() double
  }
