classDiagram
  direction LR

  class AutonChoices {
    <<enumeration>>
    NoAuto
    LeftAuto
    MiddleAuto
    RightAuto
    LeftAutoShoot
    MiddleAutoShoot
    RightAutoShoot
    MiddleSideDepotAuto
  }
