classDiagram
  direction LR

  class Paths {
    + getLeft1Path()$ PathPlannerPath
    + getLeft2Path()$ PathPlannerPath
    + getLeft3Path()$ PathPlannerPath
    + getLeft4Path()$ PathPlannerPath
    + getMiddle1Path()$ PathPlannerPath
    + getMiddle2Path()$ PathPlannerPath
    + getMiddle3Path()$ PathPlannerPath
    + getMiddle4Path()$ PathPlannerPath
    + getMiddle5Path()$ PathPlannerPath
    + getRight1Path()$ PathPlannerPath
    + getRight2Path()$ PathPlannerPath
    + getRight3Path()$ PathPlannerPath
    + getRight4Path()$ PathPlannerPath
    + getLeftShoot1Path()$ PathPlannerPath
    + getRightShoot1Path()$ PathPlannerPath
    + getDepotLeft1Path()$ PathPlannerPath
    + getDepotLeft2Path()$ PathPlannerPath
    + getMiddleSideDepot1Path()$ PathPlannerPath
    + getMiddleSideDepot2Path()$ PathPlannerPath
    + getMiddleSideDepot3Path()$ PathPlannerPath
  }
