classDiagram
  direction LR

  class AcquisitionConstants {
    <<final>>
    + MOTOR_CAN_ID$ int
    + P$ double
    + I$ double
    + D$ double
    + ACQUIRE_RPM$ double
    + DISPOSE_RPM$ double
  }
