classDiagram
  direction LR

  class AcquisitionSetpoint {
    <<enumeration>>
    RAISED
    LOW_RAISE
    HIGH_RAISE
    LOWERED
    - degrees double
    - AcquisitionSetpoint(double)
    + getDegrees() double
  }
