classDiagram
  direction LR

  class AcquisitionConstants {
    + MOTOR_CAN_ID$ int
    + P$ double
    + I$ double
    + D$ double
    + S$ double
    + V$ double
    + A$ double
    + INTAKE_RPM$ double
    + DISPOSE_RPM$ double
  }
