classDiagram
  direction LR

  class AcquisitionPivotConstants {
    <<final>>
    + MOTOR_CAN_ID$ int
    + P$ double
    + I$ double
    + D$ double
    - GEAR_RATIO$ double
    + ENCODER_CONVERSION_FACTOR$ double
    + ALLOWED_ERROR_DEGREES$ double
    + OPERATING_TOLERANCE$ double
    + POWER$ double
    + MAX_TRENCH_ANGLE$ double
    + MIN_ANGLE$ double
    + MAX_ANGLE$ double
    + TILT$ double
  }
