classDiagram
  direction LR

  class AutoConstants {
    + MAX_ACCELERATION_METERS_PER_SECOND_SQUARED$ double
    + MAX_SPEED$ double
    + MAX_ANGULAR_SPEED_RADIANS_PER_SECOND$ double
    + MAX_ANGULAR_SPEED_RADIANS_PER_SECOND_SQUARED$ double
    + P_X_CONTROLLER$ double
    + I_X_CONTROLLER$ double
    + D_CONTROLLER$ double
    + P_THETA_CONTROLLER$ double
    + I_THETA_CONTROLLER$ double
    + D_THETA_CONTROLLER$ double
    + THETA_CONTROLLER_CONSTRAINTS$ TrapezoidProfile.Constraints
    + ROBOT_CONFIG$ Optional~RobotConfig~
  }
