classDiagram
  direction LR

  class DriveConstants {
    + ODOMETRY_STD_DEV$ Matrix~N3,N1~
    + VISION_STD_DEVS$ Matrix~N3,N1~
    + DEFAULT_MAX_POWER$ double
    + BUMP_SLOWDOWN_POWER$ double
    + BUMP_APPROACH_SPEED_THRESHOLD$ double
    + TRACK_WIDTH$ double
    + WHEEL_BASE$ double
    - ROBOT_MAX_LENGTH$ double
    + ROBOT_SIZE_RADIUS$ double
    + FINE_ADJUSTMENT_PERCENT$ double
    + MAX_SPEED$ double
    + MAX_ANGULAR_RATE$ double
    + JOYSTICK_EXPONENT$ double
    + P$ double
    + I$ double
    + D$ double
    + ALIGNMENT_TOLERANCE_RAD$ double
    + MAX_ROTATION_POWER$ double
  }
