classDiagram
  direction LR

  class FieldConstants {
    <<final>>
    - HUB_EDGE_DISTANCE_FROM_DRIVER_STATION$ double
    - HUB_LENGTH$ double
    - HUB_CENTER_X$ double
    - HUB_CENTER_Y$ double
    + HUB_POSITION$ Translation2d
    - BUMP_WIDTH$ double
    - BUMP_DEPTH$ double
    - TRENCH_WIDTH$ double
    - LEFT_TRENCH_Y_OFFSET$ double
    - RIGHT_TRENCH_Y_OFFSET$ double
    - LEFT_BUMP_Y_OFFSET$ double
    - RIGHT_BUMP_Y_OFFSET$ double
    - RED_SIDE_DISTANCE$ double
    - BUMP$ Rectangle2d
    - BLUE_LEFT_BUMP$ Rectangle2d
    - BLUE_RIGHT_BUMP$ Rectangle2d
    - RED_LEFT_BUMP$ Rectangle2d
    - RED_RIGHT_BUMP$ Rectangle2d
    + BUMP_RECTANGLES$ List~Rectangle2d~
    - TRENCH$ Rectangle2d
    - BLUE_LEFT_TRENCH$ Rectangle2d
    - BLUE_RIGHT_TRENCH$ Rectangle2d
    - RED_LEFT_TRENCH$ Rectangle2d
    - RED_RIGHT_TRENCH$ Rectangle2d
    + TRENCH_RECTANGLES$ List~Rectangle2d~
    + targetPosition()$ Translation2d
  }
