classDiagram
  direction LR

  class HopperExtensionConstants {
    + MOTOR_CAN_ID$ int
    + P$ double
    + I$ double
    + D$ double
    + S$ double
    + V$ double
    + A$ double
    + FORWARD_RPM$ double
    + BACKWARD_RPM$ double
  }
