classDiagram
  direction LR

  class KickerConstants {
    + KICKER_CAN_ID$ int
    + FEEDER_CAN_ID$ int
    + KICKER_P$ double
    + KICKER_I$ double
    + KICKER_D$ double
    + FEEDER_P$ double
    + FEEDER_I$ double
    + FEEDER_D$ double
    + KICKER_SHOOT_RPM$ double
    + KICKER_REVERSE_RPM$ double
    + FEEDER_SHOOT_RPM$ double
    + FEEDER_REVERSE_RPM$ double
  }
