classDiagram
  direction LR

  class NeoMotorConstants {
    + NEO_FREE_SPEED_RPM$ double
    + VORTEX_FREE_SPEED_RPM$ double
    + NEO_550_FREE_SPEED_RPM$ double
    + MAX_NEO_CURRENT$ int
    + MAX_VORTEX_CURRENT$ int
    + MAX_NEO_550_CURRENT$ int
    + MIN_POWER$ double
    + MAX_POWER$ double
    + BATTERY_VOLTAGE$ double
  }
