classDiagram
  direction LR

  class ShooterFormula {
    <<static inner>>
    - slope double
    - yIntercept double
    - min double
    - max double
    - angle double
    + ShooterFormula(double,double,double,double,double)
    + getAngle() double
    + getMin() double
    + getMax() double
    + getSlope() double
    + setSlope(double) void
    + getYIntercept() double
    + setYIntercept(double) void
    + getShooterRPM(double) double
  }
