classDiagram
  direction LR

  class SwerveConstants {
    <<final>>
    - STEER_GAINS$ Slot0Configs
    - DRIVE_GAINS$ Slot0Configs
    + AUTON_DRIVING_MOTOR_NEUTRAL_MODE$ NeutralModeValue
    + TELEOP_DRIVING_MOTOR_NEUTRAL_MODE$ NeutralModeValue
    - STEER_CLOSED_LOOP_OUTPUT$ ClosedLoopOutputType
    - DRIVE_CLOSED_LOOP_OUTPUT$ ClosedLoopOutputType
    - DRIVE_MOTOR_TYPE$ DriveMotorArrangement
    - STEER_MOTOR_TYPE$ SteerMotorArrangement
    - STEER_FEEDBACK_TYPE$ SteerFeedbackType
    - SLIP_CURRENT$ Current
    - DRIVE_INITIAL_CONFIGS$ TalonFXConfiguration
    - STEER_INITIAL_CONFIGS$ TalonFXConfiguration
    - ENCODER_INITIAL_CONFIGS$ CANcoderConfiguration
    - PIGEON_CONFIGS$ Pigeon2Configuration
    + CAN_BUS$ CANBus
    + SPEED_AT_12_VOLTS$ LinearVelocity
    - COUPLE_RATIO$ double
    - DRIVE_GEAR_RATIO$ double
    - STEER_GEAR_RATIO$ double
    - WHEEL_RADIUS$ Distance
    - INVERT_LEFT_SIDE$ boolean
    - INVERT_RIGHT_SIDE$ boolean
    - PIGEON_ID$ int
    - STEER_INERTIA$ MomentOfInertia
    - DRIVE_INERTIA$ MomentOfInertia
    - STEER_FRICTION_VOLTAGE$ Voltage
    - DRIVE_FRICTION_VOLTAGE$ Voltage
    + DRIVETRAIN_CONSTANTS$ SwerveDrivetrainConstants
    - CONSTANT_CREATOR$ SwerveModuleConstantsFactory
    - FRONT_LEFT_DRIVE_MOTOR_ID$ int
    - FRONT_LEFT_STEER_MOTOR_ID$ int
    - FRONT_LEFT_ENCODER_ID$ int
    - FRONT_LEFT_ENCODER_OFFSET$ Angle
    - FRONT_LEFT_STEER_MOTOR_INVERTED$ boolean
    - FRONT_LEFT_ENCODER_INVERTED$ boolean
    - FRONT_LEFT_X_POS$ Distance
    - FRONT_LEFT_Y_POS$ Distance
    - FRONT_RIGHT_DRIVE_MOTOR_ID$ int
    - FRONT_RIGHT_STEER_MOTOR_ID$ int
    - FRONT_RIGHT_ENCODER_ID$ int
    - FRONT_RIGHT_ENCODER_OFFSET$ Angle
    - FRONT_RIGHT_STEER_MOTOR_INVERTED$ boolean
    - FRONT_RIGHT_ENCODER_INVERTED$ boolean
    - FRONT_RIGHT_X_POS$ Distance
    - FRONT_RIGHT_Y_POS$ Distance
    - BACK_LEFT_DRIVE_MOTOR_ID$ int
    - BACK_LEFT_STEER_MOTOR_ID$ int
    - BACK_LEFT_ENCODER_ID$ int
    - Back_LEFT_ENCODER_OFFSET$ Angle
    - BACK_LEFT_STEER_MOTOR_INVERTED$ boolean
    - BACK_LEFT_ENCODER_INVERTED$ boolean
    - BACK_LEFT_X_POS$ Distance
    - BACK_LEFT_Y_POS$ Distance
    - BACK_RIGHT_DRIVE_MOTOR_ID$ int
    - BACK_RIGHT_STEER_MOTOR_ID$ int
    - BACK_RIGHT_ENCODER_ID$ int
    - BACK_RIGHT_ENCODER_OFFSET$ Angle
    - BACK_RIGHT_STEER_MOTOR_INVERTED$ boolean
    - BACK_RIGHT_ENCODER_INVERTED$ boolean
    - BACK_RIGHT_X_POS$ Distance
    - BACK_RIGHT_Y_POS$ Distance
    + FRONT_LEFT$ SwerveModuleConstants
    + FRONT_RIGHT$ SwerveModuleConstants
    + BACK_LEFT$ SwerveModuleConstants
    + BACK_RIGHT$ SwerveModuleConstants
  }
