classDiagram
  direction LR

  class VisionConstants {
    <<final>>
    + TABLE_NAME$ String
    + VALUES_TOPIC$ String
    + RECORDING_TOPIC$ String
    + STREAM_CAM_0$ String
    + ENABLED_0_TOPIC$ String
    + ENABLED_1_TOPIC$ String
    + WIDTH$ double
    + HEIGHT$ double
    + FOV$ double
    + DRIVE_P$ double
    + DRIVE_I$ double
    + DRIVE_D$ double
    + SPIN_P$ double
    + SPIN_I$ double
    + SPIN_D$ double
    + SPIN_SETPOINT$ double
    + APRIL_TAG_AREA$ double
    + TAG_LAYOUT$ AprilTagFieldLayout
    - LEFT_CAMERA_X_OFFSET$ double
    - LEFT_CAMERA_Y_OFFSET$ double
    - LEFT_CAMERA_Z_OFFSET$ double
    + ROBOT_TO_LEFT_CAM$ Transform3d
    + ROBOT_TO_LEFT_CAM_NAME$ String
    - BACK_CAMERA_X_OFFSET$ double
    - BACK_CAMERA_Y_OFFSET$ double
    - BACK_CAMERA_Z_OFFSET$ double
    + ROBOT_TO_BACK_CAM$ Transform3d
    + ROBOT_TO_BACK_CAM_NAME$ String
    + SINGLE_TAG_STD_DEVS$ Matrix~N3,N1~
    + MULTI_TAG_STD_DEVS$ Matrix~N3,N1~
  }
