  Acquisition --|> SubsystemBase
  AcquisitionCommand *-- Acquisition
  AcquisitionCommand *-- IntakeDirection
  AcquisitionCommand --|> Command
  AcquisitionCommand ..> IntakeDirection
  AdjustHoodCommand *-- DriveTrain
  AdjustHoodCommand *-- Shooter
  AdjustHoodCommand *-- ShooterHood
  AdjustHoodCommand --|> Command
  AlignCommand *-- DriveTrain
  AlignCommand *-- SwagLights
  AlignCommand --|> Command
  Auton *-- DriveTrain
  Auton --|> SequentialCommandGroup
  AutonSelector *-- AutonChoices
  AutonSelector ..> Auton
  AutonSelector ..> DepotAuto
  AutonSelector ..> LeftPreloadAuto
  AutonSelector ..> LeftTrenchAuto
  AutonSelector ..> MiddlePreloadAuto
  AutonSelector ..> RightPreloadAuto
  AutonSelector ..> RightTrenchAuto
  AutonSelector ..> ShooterSysID
  Dashboard *-- AutonChoices
  Dashboard *-- DashboardValue
  Dashboard *-- EntryDashboardValue
  Dashboard *-- SendableDashboardValue
  Dashboard *-- SuppliedDashboardValue
  Dashboard --|> SubsystemBase
  Dashboard ..> DashboardValue
  Dashboard ..> EntryDashboardValue
  Dashboard ..> SendableDashboardValue
  Dashboard ..> SuppliedDashboardValue
  DepotAuto --|> Auton
  DepotAuto ..> AcquisitionCommand
  DepotAuto ..> AdjustHoodCommand
  DepotAuto ..> AlignCommand
  DepotAuto ..> HopperExtensionCommand
  DepotAuto ..> ShootCommand
  DriverJoystick *-- DriveTrain
  DriverJoystick *-- ShooterHood
  DriverJoystick *-- Telemetry
  DriverJoystick --|> XboxController1038
  DriverJoystick ..> AdjustHoodCommand
  DriverJoystick ..> AlignCommand
  DriverJoystick ..> ObstacleAlignCommand
  DriverJoystick ..> RetractHoodCommand
  DriverJoystick ..> Telemetry
  DriveTrain --|> Subsystem
  DriveTrain --|> SwerveDrivetrain
  EntryDashboardValue --|> DashboardValue
  HopperExtension --|> SubsystemBase
  HopperExtensionCommand *-- ExtensionDirection
  HopperExtensionCommand *-- HopperExtension
  HopperExtensionCommand --|> Command
  HopperExtensionCommand ..> ExtensionDirection
  HubActivationDetectionCommand *-- SwagLights
  HubActivationDetectionCommand --|> Command
  Indexer --|> SubsystemBase
  IndexerCommand *-- Indexer
  IndexerCommand *-- IndexerDirection
  IndexerCommand *-- Kicker
  IndexerCommand --|> Command
  IndexerCommand ..> IndexerDirection
  Kicker --|> SubsystemBase
  LeftPreloadAuto --|> Auton
  LeftPreloadAuto ..> AdjustHoodCommand
  LeftPreloadAuto ..> AlignCommand
  LeftPreloadAuto ..> HopperExtensionCommand
  LeftPreloadAuto ..> ShootCommand
  LeftTrenchAuto --|> Auton
  LeftTrenchAuto ..> AcquisitionCommand
  LeftTrenchAuto ..> AdjustHoodCommand
  LeftTrenchAuto ..> AlignCommand
  LeftTrenchAuto ..> HopperExtensionCommand
  LeftTrenchAuto ..> ShootCommand
  MiddlePreloadAuto --|> Auton
  MiddlePreloadAuto ..> AdjustHoodCommand
  MiddlePreloadAuto ..> AlignCommand
  MiddlePreloadAuto ..> HopperExtensionCommand
  MiddlePreloadAuto ..> ShootCommand
  ObstacleAlignCommand *-- DriveTrain
  ObstacleAlignCommand --|> Command
  OperatorJoystick --|> XboxController1038
  OperatorJoystick ..> AcquisitionCommand
  OperatorJoystick ..> HopperExtensionCommand
  OperatorJoystick ..> RetractHoodCommand
  OperatorJoystick ..> ShootCommand
  RetractHoodCommand *-- ShooterHood
  RetractHoodCommand --|> Command
  RightPreloadAuto --|> Auton
  RightPreloadAuto ..> AdjustHoodCommand
  RightPreloadAuto ..> AlignCommand
  RightPreloadAuto ..> HopperExtensionCommand
  RightPreloadAuto ..> ShootCommand
  RightTrenchAuto --|> Auton
  RightTrenchAuto ..> AcquisitionCommand
  RightTrenchAuto ..> AdjustHoodCommand
  RightTrenchAuto ..> AlignCommand
  RightTrenchAuto ..> HopperExtensionCommand
  RightTrenchAuto ..> ShootCommand
  Robot *-- Auton
  Robot *-- AutonSelector
  Robot *-- DriveTrain
  Robot *-- SwagLights
  Robot *-- Vision
  Robot --|> TimedRobot
  Robot ..> HubActivationDetectionCommand
  SendableDashboardValue --|> DashboardValue
  ShootCommand *-- Acquisition
  ShootCommand *-- DriveTrain
  ShootCommand *-- Indexer
  ShootCommand *-- Kicker
  ShootCommand *-- Shooter
  ShootCommand *-- SwagLights
  ShootCommand --|> Command
  Shooter --|> SubsystemBase
  ShooterConstants *-- ShooterFormula
  ShooterConstants ..> DashboardValue
  ShooterConstants ..> ShooterFormula
  ShooterFormula *-- DashboardValue
  ShooterFormula ..> DashboardValue
  ShooterHood --|> SubsystemBase
  ShooterSysID *-- Shooter
  ShooterSysID --|> Auton
  SuppliedDashboardValue --|> DashboardValue
  SwagLights *-- OperatorStates
  SwagLights *-- RobotStates
  SwagLights --|> Subsystem
  SwagLights ..> OperatorStates
  SwagLights ..> RobotStates
  Vision --|> SubsystemBase
  XboxController1038 *-- PovPositions
  XboxController1038 --|> CommandXboxController
  XboxController1038 ..> PovPositions
