  Robot --|> TimedRobot
  XboxController1038 --|> CommandXboxController
  PovPositions *-- XboxController1038
  DriverJoystick --|> XboxController1038
  OperatorJoystick --|> XboxController1038
  ShooterModule *-- Shooter
  Hood *-- ShooterHoods
  DashboardValue *-- Dashboard
  ShooterFormula *-- ShooterConstants
  ShooterModuleConstants *-- ShooterConstants
  AutonChoice *-- AutonSelector
  AutonFactory *-- AutonSelector
  Mode *-- AcquisitionCommand
  Mode *-- IndexerCommand
  PivotSetpoint *-- AcquisitionPivotConstants
  RobotStates *-- SwagLights
  OperatorStates *-- SwagLights

  Auton --|> SequentialCommandGroup
  LeftAuto --|> Auton
  LeftAutoShoot --|> Auton
  MiddleAutoShoot --|> Auton
  RightAutoShoot --|> Auton
  LeftAutoDepotShoot --|> Auton

  ShootCommand --|> Command
  AlignCommand --|> Command
  AdjustHoodsCommand --|> Command
  RetractHoodsCommand --|> Command
  AcquisitionCommand --|> Command
  AcquisitionPivotCommand --|> Command
  AcquisitionPivotTrenchRetract --|> Command
  IndexerCommand --|> Command

  Main ..> Robot
  Robot *-- AutonSelector
  Robot *-- SwagLights
  Robot *-- DriveTrain
  Robot *-- Vision
  Robot ..> Auton
  AutonSelector ..> Dashboard
