classDiagram
  direction LR

  class AcquisitionCommand {
    - intake Acquisition
    - direction IntakeDirection
    + AcquisitionCommand(IntakeDirection)
    + initialize() void
    + isFinished() boolean
    + end(boolean) void
  }
