classDiagram
  direction LR

  class AcquisitionPivotCommand {
    - acquisition Acquisition
    - setpoint AcquisitionSetpoint
    + AcquisitionPivotCommand(AcquisitionSetpoint)
    + initialize() void
    + isFinished() boolean
  }
