classDiagram
  direction LR

  class AdjustHoodsCommand {
    - shooterHoods ShooterHoods
    - shooter Shooter
    - driveTrain DriveTrain
    + AdjustHoodsCommand()
    + execute() void
    + isFinished() boolean
  }
