classDiagram
  direction LR

  class HopperExtensionCommand {
    - extension HopperExtension
    - direction ExtensionDirection
    + HopperExtensionCommand(ExtensionDirection)
    + initialize() void
    + isFinished() boolean
    + end(boolean) void
  }
