classDiagram
  direction LR

  class HubActivationDetectionCommand {
    + SECONDS_BEFORE_HUB_ACTIVATION : double
    + HubActivationDetectionCommand(DoubleConsumer)
    + execute() : void
    + end(boolean) : void
    + isHubEnablingSoon() : boolean
  }
