classDiagram
  direction LR

  class IndexerCommand {
    - indexer Indexer
    - direction IndexerDirection
    - kicker Kicker
    + IndexerCommand(IndexerDirection)
    + initialize() void
    + isFinished() boolean
    + end(boolean) void
  }
