classDiagram
  direction LR

  class ShootCommand {
    - indexer Indexer
    - kicker Kicker
    - shooter Shooter
    - driveTrain DriveTrain
    - swagLights SwagLights
    - acquisition Acquisition
    + ShootCommand()
    + execute() void
    + isFinished() boolean
    + end(boolean) void
  }
