classDiagram
  direction LR

  class ShootCommand {
    - HOOD_SERVO_MOVE_TIME$ double
    - pivot AcquisitionPivot
    - indexer Indexer
    - kicker Kicker
    - shooter Shooter
    - driveTrain DriveTrain
    - dashboard Dashboard
    - swagLights SwagLights
    - timer Timer
    - tiltAcquisitionSupplier BooleanSupplier
    + ShootCommand()
    + ShootCommand(BooleanSupplier)
    + initialize() void
    + execute() void
    + isFinished() boolean
    + end(boolean) void
  }
