classDiagram
  direction LR

  class RectangleUtils {
    - RectangleUtils()
    + drivingThroughRect(List~Rectangle2d~,Translation2d,double,double)$ boolean
    + inRect(List~Rectangle2d~,Translation2d)$ boolean
    - drivingThroughRect(Rectangle2d,Translation2d,double,double)$ boolean
    - isInRect(Rectangle2d,Translation2d)$ boolean
    - isWithinRobotRadius(Translation2d,Translation2d)$ boolean
  }
